### ISSUE TITLE
Send to brainlife and run DWI pipeline button not working

### ISSUE THREAD

**Issue by bendichter** [brainlife/ezbids#103]
<img width="757" alt="image" src="https://github.com/brainlife/ezbids/assets/844306/55336ffd-16bf-4b4a-bff8-6d8497519c44">

When I press this I get re-routed to brainlife but there is a red error message in the bottom right indicating that the transfer did not work.

**Comment by dlevitas** [comment]
@bendichter this might be related to a server issue we're experiencing, we'll let you know once that's resolved.

To clarify, are you logged into your brainlife.io account?

**Comment by dlevitas** [comment]
@bendichter apologies for not responding sooner. This was recently fixed and should now work properly. Let us know if you continue to encounter any issues.
