### ISSUE TITLE
Other modalities in ezbids

### ISSUE THREAD

**Issue by julia-pfarr** [brainlife/ezbids#121]
Hi, I wanted to ask if you are planning on including other modalities in ezbids? 

Background: I work as a Data Steward for two large collaborative research center in Germany. We have many different datatypes (mri, eeg, beh, physio, physio-eyetrack) but still want to provide all researchers with a "common" workflow (meaning, the researchers should be provided with the same scope of functions for a tool, no matter which modality they work with). BIDS is already a blessing for us but we do often notice that the researchers in our CRC are somewhat overwhelmed with the different converters, installations, and specs. So I was thinking about developing something just like ezbids but including the different modalities. Is that something you are already working on/planning on working on or will you stay with the modalities currently included?

**Comment by dlevitas** [comment]
Hi @julia-pfarr,

A long-term goal of ours is indeed to include additional modalities specified by BIDS, however, I can't give a specific timeline of when that would be. Currently ezBIDS supports the following modalities:
- MRI
- DWI
- task events 
- Perfusion (ASL)
- MEG
- PET

Our team is most knowledgable regarding MRI and DWI data, so when we've expanded modality support we often reach out to collaborators for guidance regarding how the specific data are typically collected, and any test data they can provide for validation purposes. 

If you feel that a potential collaboration, to include additional modality support to ezBIDS, would be fruitful, we'd be happy to discuss how that can be achieved.

**Comment by julia-pfarr** [comment]
Thank you for the quick reply! I am currently co-developing the converter for the new physio-eyetrack spec (BEP20) which will be released soon, so I could definitely help with including this modality. However, I understand that including new modalities takes time and is a lot of work. And the physio-eyetrack modality might not be the first to be included next. It's just the modality that is the most common in the CRCs I work in (~80% work with eyetrack or beh). 

In any way, I would be very happy to discuss a potential collaboration whenever you decide to tackle this goal :-)

**Comment by dlevitas** [comment]
> I am currently co-developing the converter for the new physio-eyetrack spec (BEP20) which will be released soon, so I could definitely help with including this modality

We prefer BEPs to be merged into the BIDS specification before providing support, but given that BEP020 appears to be nearing the finish line, I'd be happy to discuss it. 

Also happy to discuss `beh` support. 

For these discussions, I can be reached at my institutional email (dlevitas@iu.edu)

**Comment by captainnova** [comment]
Hi @dlevitas,

> ezBIDS supports the following modalities:
>     * MRI
>     * DWI
>     * task events
>     * Perfusion (ASL)
>     * MEG
>     * PET

When you call DWI a "modality", are you specifically referring to [BEP016](https://github.com/bids-standard/bids-bep016), which is Diffusion weighted imaging _derivatives_, or diffusion weighting imaging in general? Because DWI/dMRI and ASL are kinds of MRI, acquired with MR scanners, so it seems like it would be better to adhere to the established DICOM practice of not conflating sequence (or in PET, radioligand) with "modality". I know this sounds persnickety, but it is likely confusing to downstream users of BIDS datasets, who may be from other fields and unfamiliar with MRI.

**Comment by dlevitas** [comment]
Hi @captainnova,


> When you call DWI a "modality", are you specifically referring to [BEP016](https://github.com/bids-standard/bids-bep016), which is Diffusion weighted imaging _derivatives_, or diffusion weighting imaging in general?

I was referring to diffusion weighting imaging in general.


> DWI/dMRI and ASL are kinds of MRI, acquired with MR scanners, so it seems like it would be better to adhere to the established DICOM practice of not conflating sequence (or in PET, radioligand) with "modality". I know this sounds persnickety, but it is likely confusing to downstream users of BIDS datasets,

Agreed, I was being overly colloquial. I've edited my previous response to use the BIDS spec terminology ("Data type"), to be more precise. Thanks for pointing this out.

**Comment by captainnova** [comment]
Thank you! I'm sorry to police colloquiality so zealously. I wasn't worried about your response in the forum, just that it might have been indicative of BIDS terminology.
