### ISSUE TITLE
option to run locally and automating via command line

### ISSUE THREAD

**Issue by vikramraobm** [brainlife/ezbids#125]
Hello,

I am looking to use ezbids for automatic sorting of sequences and was wondering if there is a way to do this 1)  locally without transferring the data  and also  2) run it via command line.  i found solution to (1) via docker and using localhost:3000 and using the web interface, however, it would be extremely useful if that can be automated via CLI as well. Any suggestions on how to go about it?

**Comment by dlevitas** [comment]
Hi @vikramraobm,

Thanks for reaching out. Glad to hear that you were able to set up ezBIDS locally.


> it would be extremely useful if that can be automated via CLI as well. Any suggestions on how to go about it?

Unfortunately, ezBIDS does not have CLI options. This is purposeful, as ezBIDS caters to researcher who aren't as comfortable using the command line (terminal) or do not want to spend additional time learning the idiosyncrasies of a BIDS conversion tool. Furthermore, there already exist several other CLI BIDS converters, so we didn't want to reinvent the wheel. Lastly, ezBIDS operates under the assumption that BIDS conversion cannot be fully automated; users should check to ensure their data are correctly converted. 

There is however the ability to download a template once you're finished with an ezBIDS session that can be used with subsequent uploads (of the same dataset). This auto-fills fields, meaning there's less point-and-click.
