### ISSUE TITLE
docker version of ezbids failed to start

### ISSUE THREAD

**Issue by madeleinebarter** [brainlife/ezbids#127]
I am trying to run ezBIDS on Docker Desktop on a Mac. I installed Docker, Docker Compose, and the recommended version of Node. However, when I try to run it I receive the following message when it self-terminates: Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container brainlife_ezbids-api is unhealthy

I'm not sure wherein the issue lies and would appreciate any feedback. I have verified that Node is using v20.11.0, but I am unsure which version of npm to use. I have tried the 10.7.0 version and the 9.6.3 version. The only thing that I can think of that would be the issue is npm, because when I try to start up ezBIDS there appears to be an issue with npm, see the attached image.
<img width="555" alt="Screenshot 2024-07-19 at 3 02 15 PM" src="https://github.com/user-attachments/assets/eeef748e-ea94-4cb1-99e2-94d23d395e2f">

I am also able to launch the local ezBIDS website on Chrome, but it has trouble with uploading files, I tried uploading the data file from ezBIDS_tutorial_data.

Additionally, I looked at Docker while the ezBIDS website was open on Chrome, and it appears that in the ezbids container, brain life_ezbids-handler was created but not running.

**Comment by madeleinebarter** [comment]
I ran an npm audit report and got this:

<img width="842" alt="Screenshot 2024-07-19 at 4 04 19 PM" src="https://github.com/user-attachments/assets/a82798b2-9d59-4ce6-9fc7-8dd2122da32a">

**Comment by dlevitas** [comment]
Hi @madeleinebarter  thanks for reaching out.

Can you provide the specifications for the following:

- your Mac
- Docker version
- Docker Compose version


And just so we're on the same page, are you doing the following in your terminal:
1. `cd /path/to/where/you/want/to/install/ezbids`
2. `git clone https://github.com/brainlife/ezbids`
3. `cd ezbids && ./dev.sh -d`

For `npm`, I think the version we use is `8.11.0` so you could try installing that version specifically. 

You may need to delete the current docker containers/volumes when restarting.

**Comment by madeleinebarter** [comment]
Thanks! I am working on a 2023 Mac Studio with an Apple M2 Max chip and I am using those steps to run it in Docker. I am using Docker Desktop, and I attached an image with all the versions.
<img width="733" alt="Screenshot 2024-07-19 at 4 16 16 PM" src="https://github.com/user-attachments/assets/3c2072aa-d11b-453f-b58a-f5a7dde5965a">

**Comment by dlevitas** [comment]
Thanks for this information. I would suggest trying npm version `8.11.0` and seeing if that resolves your issue. I've never tried using Docker Desktop for building ezBIDS, so you may also consider running the commands in your terminal directly. 

Let me know if your problem persists.

**Comment by madeleinebarter** [comment]
I ran it directly in my terminal, and I tried running it again using npm version 8.11.0 and node v20.11.0, and I still am without any success.

But I asked ChatGPT (with a lot of specifics about the problem), who directed me to the packages.json file where I change multer to 1.4.4-lts.1 and it finally ran correctly!

**Comment by dlevitas** [comment]
That's great to hear. I'll look into the `package.json` fix myself and update the documentation if need be.
