### ISSUE TITLE
Similar code for "Determine unique series_id" value in lib.funcQA and lib.setRun

### ISSUE THREAD

**Issue by soichih** [brainlife/ezbids#19]
This code
> https://github.com/brainlife/ezbids/blob/8c90822ad4d331079ad20c983bdfb5936bc75978/ui/src/lib.js#L10

Is too much like the code in setRun function. They should be refactored.

**Comment by dlevitas** [comment]
Fixed in [b1a7f4b](https://github.com/brainlife/ezbids/commit/b1a7f4bf7cb903524bb2458fed2846a8f0ffe742)
