### ISSUE TITLE
series_id must not exist in series list

### ISSUE THREAD

**Issue by soichih** [brainlife/ezbids#20]
series_id should only exist in object level to map each object to specific series that it belongs to. 

![image](https://user-images.githubusercontent.com/923896/118045843-7790e800-b346-11eb-8b2e-abf38dfd3ef2.png)

I think we were storing this in case we might sort the series list in UI but we wanted to preserve linking between series information and each object, but I think it just makes things buggy (currently there is a bug caused by this -- I will file another issue).

**Comment by dlevitas** [comment]
Fixed in in [b1a7f4b](https://github.com/brainlife/ezbids/commit/b1a7f4bf7cb903524bb2458fed2846a8f0ffe742)
