### ISSUE TITLE
SeriesNumber / series_id mapping is wrong with analyzer.py

### ISSUE THREAD

**Issue by soichih** [brainlife/ezbids#21]
I have 3 unique series detected by analyzer.

![image](https://user-images.githubusercontent.com/923896/118046201-fede5b80-b346-11eb-876b-72901b7f977f.png)

The first one (series_id 0) contains SeriesNumber 3, 
The second one (series_id 1) contains SeriesNumber 4
The last one (series_id 2) contains SeriesNumber 5.

However, when I go to object mapping page, I see an object with SeriesNumber 5 using series_id 1 - instead of 2. 

![image](https://user-images.githubusercontent.com/923896/118046075-cd659000-b346-11eb-8408-d5d184f77d41.png)

Also, I see the phantom series with SeriesNumber 7 (which doesn't exist in the series page) showing up on the override page *and* it's using series_id 1 which is for SeriesNumber 4. 

![image](https://user-images.githubusercontent.com/923896/118046119-dd7d6f80-b346-11eb-9f05-2b6bb447a9e2.png)

I think something is broken with analyzer.py.

**Comment by dlevitas** [comment]
Issue is that variables `series_id` and `SeriesNumber` represent two separate things, but are confusing to user and can lead to improper entries on the UI. Solution is to rename `series_id` to `series_idx`
