### ISSUE TITLE
Pare back auto populate

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/ezbids#35]
Some of the auto populate entries (e.g. for license & authors) may have some users (who aren't paying close attention) agree to certain metadata that isn't reflective of their data set.  

Recommend leaving such entries blank by default.

**Comment by soichih** [comment]
Thanks for the comment. I put them there as a default "placeholder" just to help with test/debug as some of those fields are required by BIDS spec...?? @dlevitas do you have any preference?

**Comment by dlevitas** [comment]
I have no issue with leaving the License and Authors entries blank by default.

**Comment by dlevitas** [comment]
This fix has been applied to the ezBIDS test instance, but won't appear to users until we update production.
