### ISSUE TITLE
Failure to infer type from session names

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/ezbids#36]
A recent run of ezbids with data using the following session names:

t1_mpr_tra_05iso_ND
tse_vfl

failed to return identifications of types (T1 and T2) respectively, resulting in default to "exclude" type.

It was suggested that t1 / mpr (mprage) should be sufficient information to infer correct type in that case.

**Comment by dlevitas** [comment]
ezBIDS does what it can to identify acquisition `DataType` but if not it will default to "exclude" and have the user make the change, if necessary. The reason for this is that we're more concerned about misidentifications that uses may not check for accuracy. For example, we feel it's worse for ezBIDS to identify an acquisition as `anat/T1w` when in reality it's `anat/T2w`, then for ezBIDS to  identify it as "exclude" and let the user change it.

As we get more users and test data, we can improve the ezBIDS identification heuristic. Should be able to do it with the `t1_mpr_tra_05iso_ND` example you provided.
