### ISSUE TITLE
Add B0FieldIdentifier and B0FieldSource

### ISSUE THREAD

**Issue by dlevitas** [brainlife/ezbids#38]
Source: [bids-standard/bids-specification#622](https://github.com/bids-standard/bids-specification/pull/622) 

Also ties into our discussion on whether we want to keep the automated fmap `IntendedFor` mapping or let users have more say over the mapping heuristic

**Comment by soichih** [comment]
We were discussing this somewhere else (on slack?). Basically, all we need to do is to auto generate the B0FieldIdentifier (maybe just use series #?) and set B0FieldSource on all objects that are listed in Object/IntendedFor array . Am I thinking it right?

**Comment by dlevitas** [comment]
Yes, that seems to be the gist of it, though I'm not quite sure how it relates to the different [fieldmap cases](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#types-of-fieldmaps). Only cases 1 & 4 have examples, but maybe that's only where it applies.
