### ISSUE TITLE
Improve resizing of long help-text boxes

### ISSUE THREAD

**Issue by francopestilli** [brainlife/ezbids#41]
Text boxes showing BIDS help for specific fields seem to be cut off
![image](https://user-images.githubusercontent.com/2119795/144965298-329e6400-ea6e-4b56-a641-b40e5ce8d8c6.png)

**Comment by soichih** [comment]
This should be fixed in the current dev version of ezBIDS. We should be release the new version by the end of this week (right @dlevitas?)

**Comment by dlevitas** [comment]
If its alright, let's hold off updating ezBIDS until next week. 

Once updated, issues like this will be resolved.

**Comment by dlevitas** [comment]
Now fixed in latest ezBIDS update
