### ISSUE TITLE
FLAIR

### ISSUE THREAD

**Issue by francopestilli** [brainlife/ezbids#42]
It looks like this FLAIR image was not automatically recognized
![image](https://user-images.githubusercontent.com/2119795/144965920-b232f170-3edb-46fb-abf2-88a54a62f4e8.png)

**Comment by dlevitas** [comment]
The reason it's being set to "exclude" seems to be that it's a multi-echo anatomical acquisition. For anatomical acquisitions, ezBIDS looks for the combined RMS, not the individual echoes.
