### ISSUE TITLE
Add '001', '002', '003' etc - instead of '1', '2', '3', etc

### ISSUE THREAD

**Issue by francopestilli** [brainlife/ezbids#43]
https://github.com/brainlife/ezbids/blob/7848dbb9cd52628e2e2e45677a41eefcf721bc56/ui/src/libUnsafe.ts#L319

@dlevitas can we please default to run numbers with leading zeros (better for sorting on unix/linux and predicting larger datasets). What I mean is that, instead of filling in run number as
run1-
run2-
run3
etc

we should be filling in as
run001-
run002-
run003-
etc

**Comment by dlevitas** [comment]
@francopestilli according to the BIDS specification:
`If several scans with the same acquisition parameters are acquired in the same session, they MUST be indexed with the run-<index> entity: _run-1, _run-2, _run-3, and so on (only nonnegative integers are allowed as run labels).`

Based on this, ezBIDS doesn't zero-pad any entity label that requires an index (i.e. integer) value. 

Newer versions of fMRIprep adhere more strictly to the use of run integer values. For example, if someone's BIDS dataset used `run-01`, the fMRIPrep derivatives output would be `run-1`. I believe this has to do with the use of PyBIDS. 

I agree that not zero-padding can be visually unappealing from a sorting perspective with >10 runs. For now, I think the default ezBIDS behavior is correct and should remain this way unless the BIDS specification changes.

**Comment by soichih** [comment]
I agree with @dlevitas This is dictated by BIDS specification so we can't change it. 

`sub-` on the other hand, *can be* 0-padded and we already do that.
