### ISSUE TITLE
Recommend updating Niivue

### ISSUE THREAD

**Issue by hanayik** [brainlife/ezbids#48]
@soichih, I would recommend updating Niivue to the most recent version on npm. There have been significant changes that make Niivue more robust, and tolerant of NIFTI files stored in various orientations. The 3D rendering has also been updated. Lastly, a new options exists to disable drag and drop file loading on the canvas. This is useful if you don't want users to accidentally drop a file on the canvas (which would replace the image).

**Comment by soichih** [comment]
Thanks for letting me know! We've updated it to 0.21.1. The UI doesn't look all too different, but do we need to adjust the niivue config parameters?

![image](https://user-images.githubusercontent.com/923896/156612431-2e97261f-1377-41d2-a8c2-ebd0c4f0fd55.png)

Here is our current config parameters

https://github.com/brainlife/ezbids/blob/master/ui/src/components/niivue.vue#L46

**Comment by hanayik** [comment]
@soichih , it would be good to actually update again. Sorry about that, we had a 3D rendering bug introduced recently that was only showing up on certain devices. That bug has been fixed now. The latest Niivue should be used. The useful enabling/disabling of drag and drop is also now supported: https://github.com/niivue/niivue/blob/351cff117f04e7cd1d70c7868746fd4633569831/src/niivue.js#L83

**Comment by soichih** [comment]
OK will do! I've asked @dlevitas to help up update/reconfigure this time around.

**Comment by dlevitas** [comment]
Hi @hanayik niivue should now be updated on ezBIDS.

Thanks for reaching out.
