### ISSUE TITLE
Failed - Download error

### ISSUE THREAD

**Issue by andreifoldes** [brainlife/ezbids#49]
Hello - thanks for the tool+
I'm noticing download error consistently today at around 1.2 GB - the full file I'm trying to download is 6 GB, is there a way to check whether its client side or server side?

**Comment by dlevitas** [comment]
Hi @andreifoldes if you provide your ezBIDS URL, we can take a look at it. 

In the meantime, can you check your Downloads folder to see if the dataset zip file is there? Sometimes this is the case even when ezBIDS throws a download error. If the zip file is there, you can extract with something like this from the command line: `7za x myFolder.zip`

**Comment by dlevitas** [comment]
Not a problem, glad it was easily. In the future we can alert users to this potential issue.
