### ISSUE TITLE
issues with participant.tsv file

### ISSUE THREAD

**Issue by andreifoldes** [brainlife/ezbids#51]
Hello

When I rename my subject using the interface both the original name and my new name get inserted into the participant.file
e.g.:

sub-170322301	F	22
sub-CKOUSM	f	22

is this the expected behavior? Shouldn't participant.TSV just contain the actual datafiles (just sub-CKOUSM)?

**Comment by dlevitas** [comment]
Hi @andreifoldes,

You are correct, the participants.tsv file should only contain the information for `sub-CKOUSM`, so this seems like a bug. Would you be able to share your ezBIDS URL? We can look it over to see if there is anything odd going on.

**Comment by andreifoldes** [comment]
Yes, I just re-uploaded an already BIDS subject for demonstration purposes:
https://brainlife.io/ezbids/#6279371f4305857de59954ea

So it seems that when user renames "participant.tsv" generating procedure doesn't update the original entry, just appends the renamed entry...

**Comment by dlevitas** [comment]
@andreifoldes I'm unable to reproduce your issue. I uploaded a subject's data and went through the ezBIDS steps to `Participants Info`. I then went back to `Subjects/Session`, altered the subject ID and went back to `Participants Info` but the subject ID had been correctly updated. We might have made a fix somewhere else that inadvertently fixed your issue; would you mind uploading some data where you've had this problem and see if it persists? If so, could you share that data with us for debugging purposes?

**Comment by soichih** [comment]
@andreifoldes With a help from @dlevitas I think I was able to reproduce this (and similar issue) and I just released a patch. Please try again and if you come across the same / similar issue, please let us know!
