### ISSUE TITLE
Iterating across dictionary returns keys as strings, which cannot be indexed by strings

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/ezbids#54]
https://github.com/brainlife/ezbids/blob/104061eb9f71f1fafd9b533d5ec1e7f718204125/handler/analyzer/analyzer.py#L801

Trying to run the relevant sub-component of this line returns this error:

[x["suffixes"] for x in rule]
Traceback (most recent call last):

  File "/tmp/ipykernel_84714/87350421.py", line 1, in <module>
    [x["suffixes"] for x in rule]

  File "/tmp/ipykernel_84714/87350421.py", line 1, in <listcomp>
    [x["suffixes"] for x in rule]

TypeError: string indices must be integers

To confirm this issue I ran:

[type(x) for x in rule]
Out[65]: [str, str, str, str, str, str, str, str, str]

Maybe extracting rule.keys() and iterating across that list with a regular for loop would achieve the desired outcome?

**Comment by DanNBullock** [comment]
Maybe something is going on with how mine is loading on [this line](https://github.com/brainlife/ezbids/blob/104061eb9f71f1fafd9b533d5ec1e7f718204125/handler/analyzer/analyzer.py#L799), but it is definitely showing up as a dict:

type(rule)
Out[69]: dict

len(rule)
Out[70]: 9

rule.keys()
Out[71]: dict_keys(['nonparametric', 'parametric', 'defacemask', 'multiecho', 'multiflip', 'multiinversion', 'mp2rage', 'vfamt', 'mtr'])

datatype
Out[72]: 'anat'

datatype_suffix_rules
Out[73]: '../bids-specification/src/schema/rules/datatypes'

Is something going wrong with how I'm loading on line 799?

**Comment by dlevitas** [comment]
If you're running the sourcecode locally, can you change lines 36-40  to this:

```
datatypes_yaml = yaml.load(open("../../bids-specification/src/schema/objects/datatypes.yaml"), Loader=yaml.FullLoader)
entities_yaml = yaml.load(open("../../bids-specification/src/schema/objects/entities.yaml"), Loader=yaml.FullLoader)
suffixes_yaml = yaml.load(open("../../bids-specification/src/schema/objects/suffixes.yaml"), Loader=yaml.FullLoader)
datatype_suffix_rules = "../../bids-specification/src/schema/rules/datatypes"
entity_ordering_file = "../../bids-specification/src/schema/rules/entities.yaml"
```

**Comment by soichih** [comment]
So they updated the structures of bids-specification recently. We are still using the older version of bids specification because we haven't had the time to upgrade our code to use the new structure. Is this maybe caused by ezBIDS code expecting old structure and Dan B. is using the latest version of bids-specification?

**Comment by dlevitas** [comment]
Ah, right. I'll work on updating the analyzer to handle the new structure next week

**Comment by soichih** [comment]
We also need to update our UI codes.

**Comment by DanNBullock** [comment]
Yes, I was using the latest pull from the Bids repo, so that may be the relevant factor.
