### ISSUE TITLE
  cog_atlas_tasks 'function' object is not iterable

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/ezbids#55]
https://github.com/brainlife/ezbids/blob/104061eb9f71f1fafd9b533d5ec1e7f718204125/handler/analyzer/analyzer.py#L1186

I think it's probably because I'm running things out of order, but may be it would be a better practice to not reset this as a variable here:

https://github.com/brainlife/ezbids/blob/104061eb9f71f1fafd9b533d5ec1e7f718204125/handler/analyzer/analyzer.py#L1527

When it was formerly set as a function here:

https://github.com/brainlife/ezbids/blob/104061eb9f71f1fafd9b533d5ec1e7f718204125/handler/analyzer/analyzer.py#L52

In the end though, I guess it's just a matter of personal preference.

**Comment by dlevitas** [comment]
Good point, this is something I can go back and adjust.
