### ISSUE TITLE
Update to bids-specification 1.7.1 (once it's released)

### ISSUE THREAD

**Issue by soichih** [brainlife/ezbids#56]
ezBIDS is designed to work with bids-specification/schema with commit ID edcbfab. They've made various breaking changes to the schema and once the current dev version 1.7.1 is released we should update our code, and freeze the bids-specification to use the 1.7.1 release tag instead of using master.

**Comment by dlevitas** [comment]
In the future, should we reach out to the bids-specification to have them let us know when they push these structural changes?

**Comment by soichih** [comment]
Oh I mentioned it to @effigies last week while in Austin :)

**Comment by effigies** [comment]
We added a schema version file, and the plan is to bump it when we knowingly make breaking changes. If there are tests you could provide to ensure we don't break, we could add them to CI.

**Comment by soichih** [comment]
@effigies You mean this > https://github.com/bids-standard/bids-specification/blob/master/src/schema/SCHEMA_VERSION right?

We use bids-specification as git sub-module for ezbids, so we will do something like this.

1) We will use specific commit ID/tag for bids-specification as ezbids submodule. 
2) When a new bids-specification is released, we will look a the SCHEMA_VERSION file, and if the version number is the same, we will go ahead and update to the new commit ID. If it's different, then we will hold off on updating *or* analyze what's changed and make necessary code changes before upgrading to the latest version for our production instances.

**Comment by effigies** [comment]
Perfect. Sounds like a solid plan.
