### ISSUE TITLE
Does ezbids comply with GDPR

### ISSUE THREAD

**Issue by MasonTWells** [brainlife/ezbids#60]
Hi,

I wondered if ezbids is compliant with GDPR? I have seen that the data is stored for five days before being removed, but my concern is that if it is stored off our secure systems, it would violate data management polices here in the UK.

Any advice would be greatly appreciated. 

Best wishes,
Mason

**Comment by dlevitas** [comment]
Hi @MasonTWells ,

I'm a bit unfamiliar with the GDPR rules, as we're not in the EU. What I can say about the ezBIDS architecture and security is that  we run our infrastructure on a secure, restricted VM that only the key staff members have access to. We also store access log information in case of unauthorized access and/or data breach.

**Comment by andreifoldes** [comment]
Could this issue be sidestepped by launching the docker version of ezBIDS locally?

**Comment by dlevitas** [comment]
@andreifoldes I believe so, yes. We're currently working on an installable version of ezBIDS for users, so that data upload won't be necessarily. We should have a working version up around the end of the year.
