### ISSUE TITLE
Removing objects in Dataset Review doesn't update Series Mapping

### ISSUE THREAD

**Issue by andreifoldes** [brainlife/ezbids#61]
Greetings,

I had to exclude some objects in the Dataset Review and I noticed that the BIDS review in the end I got
	1: [ERR] 'IntendedFor' field needs to point to an existing file. (code: 37 - INTENDED_FOR)

I think it would be cool if after the "Datasets Review" Series Mapping would be refreshed?

**Comment by andreifoldes** [comment]
Weirdly enough even when manually deleting the "exlucded files" from the Intended for field the BIDS validator still shows the same error.

**Comment by dlevitas** [comment]
Apologies @andreifoldes for not responding to this, must have fallen through the cracks.

Over the past year we've updated how ezBIDS handles dynamic processes (e.g., user edits/modifications) on the individual pages. Issues like the one you've described here should now be correctly handled. 

Feel free to re-open if you continue encountering this. I'm unable to reproduce, so I'll assume things are now corrected.
