### ISSUE TITLE
Upload issues

### ISSUE THREAD

**Issue by andreifoldes** [brainlife/ezbids#62]
Hi I'm having trouble uploading files to Ezbids. When it reaches 100% it says failed. 
Preprocess log:
{"errno":-13,"syscall":"lstat","code":"EACCES","path":"/mnt/ezbids/workdir/62ea654828256c619386aed3/preprocess.log"}

**Comment by soichih** [comment]
Hi @andreifoldes Thank you for reporting this issue. We seem to be having some issue with our new ceph volume. We recently migrated our production instance of ezBIDS from old Jetstream instance to the new Jetstream2. We are still getting a few kinks sorted out. I will need to do some troubleshooting with the Jetstream administrator on this issue. I will report back as soon as I can.

**Comment by dlevitas** [comment]
Hi @andreifoldes this issue should now be resolved for you, apologies for the delayed response.
