### ISSUE TITLE
Trouble specifying Events

### ISSUE THREAD

**Issue by dkp** [brainlife/ezbids#68]
Dear EZ-BIDS creators,
I'm having trouble creating events correctly. There are two issues:
1) ez-bids is getting the subject name wrong and assuming there is a session.  I can correct these problems, but a session should not be required.  See https://youtu.be/EDXLidYXsVI

2) Additionally, since last week, EZ-BIDS has stopped generating the events files: sub-188_task-nad1_run-02_events.tsv, even though it continues to accept my upload and revisions as in the attached video.  Maybe I'm doing something wrong, but it seems like a recent issue.
_________________
Would it be possible to add to your excellent help on the webpage for events by providing an example of what the tsv (or csv) files should look like internally, especially in the case where subject and session are supplied in the text file instead of in the directory structure?

Thanks so much!

**Comment by dlevitas** [comment]
Hi @dkp,

Thanks for providing this video. I'm not entirely sure why ezBIDS isn't properly matching the timing files, as your file names/structure appear correct based on the example. It might have to do with the differences between Mac and Windows when it comes to specifying directory structure (i.e. "/" vs "\"). If you were to rename your file like `sub-188_task-nad1_run-02_events.tsv` then it should map properly. 

I'll have to look into why ezBIDS has stopped generating the events.tsv files, thanks for alerting us to this.

**Comment by dkp** [comment]
Sorry it took so long to get back.  You are absolutely right that on the Mac, the event files needed to be renamed.  Thank you, and sorry it took me so long to get back to testing your solution.
This is the mac example:
```bash
sub-188
├── sub-188_task-nad1_run-01_events.tsv
├── sub-188_task-nad1_run-02_events.tsv
├── sub-188_task-nad1_run-03_events.tsv
└── sub-188_task-nad1_run-04_events.tsv
```
This is the Windows example:
```bash
sub-188
├── task-nad1_run-01.tsv
├── task-nad1_run-02.tsv
├── task-nad1_run-03.tsv
└── task-nad1_run-04.tsv
```
