### ISSUE TITLE
subject contains non-alphanumeric character error

### ISSUE THREAD

**Issue by andreifoldes** [brainlife/ezbids#78]
Hello,

I'm trying out ezBIDS with a new dataset and after it correctly numerically indexed each sub at Data mapping step 1, it doesn't let me proceed after series mapping because it believes that there is a "non-alphanumeric character error" for some or all subjects.

I tried using Reset Subject Mapping, but to no avail...

[](url)
<img width="945" alt="Capture2" src="https://user-images.githubusercontent.com/7458009/231447721-60d277f7-7314-43a0-af74-3b273fb7d996.PNG">

**Comment by dlevitas** [comment]
@andreifoldes that's strange, your subject IDs look fine. Can you provide your ezBIDS URL? Feel free to email it to me (dlevitas@iu.edu).

**Comment by dlevitas** [comment]
Thanks @andreifoldes for the URL, I've pushed a fix that should address this issue. You'll need to begin a new session for the changes to take effect. Let me know if you encounter anything else or have any questions.
