### ISSUE TITLE
Echo numbers

### ISSUE THREAD

**Issue by astewartau** [brainlife/ezbids#79]
Dear ezbids authors,

Thank you for the hard work in putting this tool together! It may help to enable the use of my software on Brainlife.

I can't find how to specify echo numbers when converting to BIDS. For this reason, I cannot convert multi-echo T2*-weighted datasets to BIDS using it. 

Thanks!
Ashley

**Comment by dlevitas** [comment]
Hi @astewartau,

Thanks for reaching out. ezBIDS has the ability to assign echo numbers, so it's strange that it's not working in your case. I'll look into this, would you mind emailing me (dlevitas@iu.edu) your ezBIDS URL?
