### ISSUE TITLE
Setting IntendedFor for fmap/epi image 

### ISSUE THREAD

**Issue by dkp** [brainlife/ezbids#82]
Under Series Mapping, I set IntendedFor on the fmap/epi image (this is the reverse phase-encode B0 image for correcting the DWI image).

When I got the Dataset review, IntendedFor was set to "no-series" and I had to reset it again.

**Comment by dlevitas** [comment]
@dkp are you able to share/email me the subject's data? I'm unable to reproduce this issue with one of my datasets.

**Comment by dkp** [comment]
@dlevitas  I was using my sub-188 dataset from OSF [ezbids_dicom_188.zip](https://osf.io/w572f).

BTW, thanks for fixing the event upload issue from Mac vs Windows!  The whole interface seems cleaner and smarter than when I last tried it.  My students love your interface. I was also excited to see you thinking about offering a containerized version.  

I do wish there was some way to save and reuse the specification for the translation (the finalized.json looks promising, but I don't know how to reuse it).  Is this on your roadmap?

**Comment by dlevitas** [comment]
Thanks @dkp,

This issue should now be fixed, there was a strange indexing issue being caused by the `func/events` files. Let us know if you encounter any other issues.

**Comment by dkp** [comment]
@dlevitas 
Uh oh, so sorry to report this, but now the dataset review has gotten some weird set of values in the Intendedfor field, despite my having set those IntendedFor targets correctly in the Series Mapping ; (

![series_mapping](https://github.com/brainlife/ezbids/assets/965184/061b1771-861b-4504-bd1a-be2fc3e89f5a)

![Notification_Center](https://github.com/brainlife/ezbids/assets/965184/d59c070b-b718-444c-83a9-246f9d712f73)

**Comment by dkp** [comment]
Aha, let me recheck my dumbness ; )

**Comment by dlevitas** [comment]
I'm unable to reproduce the issue with the same subject and mismatched `sub` IDs. 

If you're using the same URL from yesterday, you would need to restart a new one to reflect the changes I made. Apologies for not making that more clear if that was the case.

**Comment by dkp** [comment]
@dlevitas It looks like that was just a mistake on my part, but it looks like the problem with IntendedFor mac vs Windows files has resurfaced ; (  
Yesterday it seemed like the specification of the events had been unified for Mac and Windows, but now that problem seems to have returned.  Was I wrong to believe the Mac/Windows thing was resolved, or did I make some other mistake (I am using the Windows format, but uploading from a Mac):

bids-validator@1.11.0
	1: [ERR] 'IntendedFor' field needs to point to an existing file. (code: 37 - INTENDED_FOR)
		./sub-188/fmap/sub-188_dir-PA_epi.nii.gz
			Evidence: func/sub-188_task-nad1_run-3_events.nii.gz

	Please visit https://neurostars.org/search?q=INTENDED_FOR for existing conversations about this issue.

**Comment by dlevitas** [comment]
It shouldn't have, the changes I made yesterday didn't touch the fix to #68. 

I don't have access to a Windows; however, for testing purposes I used your Windows layout for the events files:
`
sub-188
├── task-nad1_run-01.tsv
├── task-nad1_run-02.tsv
├── task-nad1_run-03.tsv
└── task-nad1_run-04.tsv
`
Even with this structure I didn't encounter the issue. To give me a better sense of what might be going on, could you email me your ezBIDS URL?

**Comment by dkp** [comment]
@dlevitas I don't have access to Windows either!  I am hoping for something that works for my students regardless of whether they are on Mac or Windows. I'm trying again, here: https://brainlife.io/ezbids/#6477ac2f55144c1c33fc9a53

**Comment by dlevitas** [comment]
The solution was to clear the browser cache. Before, newly pushed changes weren't being recognized, hence the validator issue.
